### PR TITLE
SEO pages

### PR DESCRIPTION
**Pull request by mgoodwingb**
SEO pages created, optimized images added, site map updated.

Please ensure this looks OK. If not, lets work to change it.

### CODE REVIEW

**Comment by andruby** [comment]
Just an FYI. Probably you already know this. The jekyll-sitemap gem used in this github page generates a sitemap.xml file for search engines by default http://www.jaswig.com/sitemap.xml

**Comment by mgoodwingb** [comment]
Thanks for this info. Is it possible for you to add the new site map and SEO pages to this sitemap.xml file? It doesn't look like they are included in the current one. I've uploaded a .txt of what we can update the .xml to that includes all new pages. 
[sitemap.txt](https://github.com/jaswig/jaswig.github.io/files/583796/sitemap.txt)

**Comment by andruby** [comment]
Have a look at jekyll sitemap https://github.com/jekyll/jekyll-sitemap

That's the gem that auto generates the sitemap.xml

**Comment by Ellegiers** [comment]
Wat denk je? Wat moet er gebeuren?
Dan vraag ik aan de developer om het uit te voeren.

Yes, this gem looks like it should generate a sitemap that includes links to all the SEO pages, but looking at http://www.jaswig.com/sitemap.xml http://www.jaswig.com/sitemap.xml - these pages don't appear. Is there a way this gem can re-generate an xml site map to see if the new pages will be added? If there is no other way, I believe manually adding an XML file to the root directory will override the auto generated sitemap.

**Comment by andruby** [comment]
Which pages aren't mentioned in the sitemap that should be mentioned?

**Comment by Ellegiers** [comment]
These pages are linked on the current site map we added manually at the bottom of the site.
I don’t know how to see the automatically created site map by the Jekyll stuff

http://www.jaswig.com/standing-desk/ http://www.jaswig.com/standing-desk/

http://www.jaswig.com/height-adjustable-desk/ http://www.jaswig.com/height-adjustable-desk/

http://www.jaswig.com/adjustable-height-desk/ http://www.jaswig.com/adjustable-height-desk/

http://www.jaswig.com/standing-table/ http://www.jaswig.com/standing-table/

http://www.jaswig.com/standing-workstation/ http://www.jaswig.com/standing-workstation/

http://www.jaswig.com/ergonomic-desk/ http://www.jaswig.com/ergonomic-desk/

http://www.jaswig.com/standing-computer-desk/ http://www.jaswig.com/standing-computer-desk/

**Pull request merged**
